=== {learning-goals}

// tag::DE[]

[[LZ-1-1]]
==== LZ 1-1: Künstliche Intelligenz und Machine Learning, Data Science, Deep Learning, Generative AI einordnen können

Die Teilnehmer:innen wissen, wie man Künstliche Intelligenz definiert und wie Machine Learning, Data Science, Deep Learning, Generative AI darin eingeordnet werden.

[[LZ-1-2]]
==== LZ 1-2: Typische allgemeine Anwendungsfälle für KI spezifizieren

Die Teilnehmer:innen wissen, wie typische allgemeine Anwendungsfälle für KI spezifiziert werden können. Dies umfasst Anwendungsfälle für z.{nbsp}B. Bilderkennung & -erzeugung, Sprachverarbeitung, Vorhersagen, Personalisierung und Anomalieerkennung.

[[LZ-1-3]]
==== LZ 1-3: Einsatzmöglichkeiten in verschiedenen Branchen und Endnutzeranwendungen kennen

Die Teilnehmer:innen kennen die möglichen Einsatzmöglichkeiten in verschiedenen Branchen, z.{nbsp}B. Marketing, Medizin, Robotik und Content-Creation. Darüber hinaus überblicken sie die Einsatzmöglichkeiten in Endnutzeranwendungen von KI. Darunter fallen z.{nbsp}B. Sprachassistenten (Chatbots) und Empfehlungssysteme (Recommender Engine).


[[LZ-1-4]]
==== LZ 1-4: Risiken bei der Anwendung von KI identifizieren

Die Teilnehmer:innen können Risiken, die bei der Anwendung von KI auftreten, identifizieren. Das können beispielsweise folgende Risiken sein:

* Halluzinationen
* Bias
* (un-)Fairness
* gesellschaftlichen Risiken wie Deepfakes, AI-enabled Cyberattacks, Safety Risks in Critical Systems, Social Manipulation, Intellectual Property Issues usw.



[[LZ-1-5]]
==== LZ 1-5: Unterschiede zu traditioneller Software verstehen

Die Teilnehmer:innen verstehen die Unterschiede von KI-Systemen zu traditioneller Software:

* Datengetrieben (bei ML) – Daten-zentrierte statt Code-zentrierte Entwicklung
* Probabilistische Ergebnisse (Non-deterministic behavior)
* Statistische Validierung
* Experimentelles Design: Unterstützung für schnelle Iteration und Testen von Modellen.
* Modellkomplexität und Interpretierbarkeit: ML-Modelle, insbesondere Deep-Learning-Modelle, können äußerst komplex sein. Der „Black-Box“-Charakter erschwert die Interpretierbarkeit und Erklärbarkeit.
* Debugging und Tests sind aufgrund des Nichtdeterminismus komplexer.
* Model Decay: Continuous monitoring und Retraining sind notwendig, um die Leistung der Modelle aufrechtzuerhalten.
* AI-spezifische Regulatorik von Branchen und auf EU-Ebene müssen berücksichtigt werden.
* Interoperabilität: Nahtlose Integration in bestehende Systeme und Technologiestacks.

[[LZ-1-6]]
==== LZ 1-6: Lösung von Problemen mittels KI oder klassischer SW-Entwicklung entscheiden

Teilnehmer:innen können entscheiden und erklären, ob und warum ein Problem mittels KI oder klassischer SW-Entwicklung zu lösen ist.

[[LZ-1-7]]
==== LZ 1-7: Rollen und deren Aufgaben sowie ihre Zusammenarbeit im Kontext von KI kennen

Die Teilnehmer:innen kennen typische Rollen und deren Aufgaben in diesen Kontexten. Die Rollen umfassen insbesondere:

Data Scientist, Data Analyst, Data Engineer, Machine Learning Engineer, MLOps Engineer, AI Architect,
Data Architect, Business Intelligence (BI) Developer, Data Governance Specialist und ML-Researcher.

Die Teilnehmer:innen wissen darüber hinaus, wie diese Rollen im Team zusammenarbeiten könnten (Team Topologies für ML-Teams).


[[LZ-1-8]]
==== LZ 1-8: KI Anwendungsfällen identifizieren und priorisieren

Die Teilnehmer:innen können KI Anwendungsfälle identifizieren und priorisieren.

[[LZ-1-9]]
==== LZ 1-9: Stärken und Grenzen von KI kennen

Die Teilnehmer:innen verstehen die Stärken und die Grenzen von KI und kennen die sog. "Jagged Technological Frontier".

[[LZ-1-10]]
==== LZ 1-10: Konzept der Productivity J-Curve in Verbindung mit KI-Technologie kennen

Dieses Phänomen hilft zu verstehen, warum Unternehmen bei der Implementierung von KI zunächst einen Produktivitätsrückgang verzeichnen können, dem bei der weiteren Entwicklung aber Produktivitätsgewinne folgen können.


// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: This the first learning goal, in category xy
tbd.
// end::EN[]
