=== {learning-goals}

// tag::DE[]
In diesem Kapitel erreichen die Teilnehmer:innen die folgenden Lernziele:

[[LZ-1-1]]
==== LZ 1-1: Definition Künstliche Intelligenz inklusive der Einordnung von Machine Learning, Data Science, Deep Learning, Generative AI

Die Teilnehmer:innen wissen wie man Künstliche Intelligenz definiert und wie Machine Learning, Data Science, Deep Learning, Generative AI darin eingeordnet werden.

[[LZ-1-2]]
==== LZ 1-2: Spezifikation typischer allgemeiner Anwendungsfälle für KI

Die Teilnehmer:innen wissen wie typische allgemeine Anwendungsfälle für KI spezifiziert werden können. Dies umfasst Anwundungsfälle für  z.B. Bilderkennung & -erzeugung, Sprachverarbeitung, Vorhersagen, Personalisierung und Anomalieerkennung.

[[LZ-1-3]]
==== LZ 1-3: Einsatzmöglichkeiten in verschiedenen Branchen

Die Teilnehmer:innen kennen die möglichen Einsatzmöglichkeiten in verschiedenen Branchen, z.B. Marketing, Medizin, Robotik und Content-Creation.

[[LZ-1-4]]
==== LZ 1-4: Einsatzmöglichkeiten in Endnutzeranwendungen

Die Teilnehmer:innen überblicken die Einsatzmöglichkeiten in Endnutzeranwendungen von KI. Darunter fallen z.B. Sprachassistenten (Chatbots) und Empfehlungssysteme (Recommender Engine).

[[LZ-1-5]]
==== LZ 1-5: Risiken bei der Anwendung von KI

Die Teilnehmer:innen kennen und verstehen die Risiken, die bei der Anwendung von KI auftreten können. Dazu gehören beispielsweise

* Halluzinationen
* Bias
* (un-)Fairness 
* gesellschaftlichen Risiken wie Deepfakes, AI-enabled Cyberattacs, Safety Risks in Critical Systems, Social Manipulation, Intellectual Property Issues usw. 


[[LZ-1-6]]
==== LZ 1-6: Unterschiede zu traditioneller Software

Die Teilnehmer:innen verstehen die Unterschiede von KI-Systemen zu tradiitoneller Software:

* Datengetrieben (bei ML) - Daten-zentrierte statt Code-zentrierte Entwicklung
* Probabilistische Ergebnisse (Non-deterministic behavior)
* Statistische Validierung
* Experimentelles Design: Unterstützung für schnelle Iteration und Testen von Modellen.
* Modellkomplexität und Interpretierbarkeit: ML-Modelle, insbesondere Deep-Learning-Modelle, können äußerst komplex sein. Der „Black-Box“-Charakter erschwert die Interpretierbarkeit und Erklärbarkeit.
* Debugging und Tests sind aufgrund des Nichtdeterminismus komplexer.
* Model Decay: Continuous monitoring und Retraining sind notwendig, um die Leistung der Modelle aufrecht zu erhalten.
* AI-spezifische Regulatorik von Branchen und auf EU-Ebene müssen berücksichtigt werden.
* Interoperabilität: Nahtlose Integration in bestehende Systeme und Technologiestacks.

[[LZ-1-7]]
==== LZ 1-7: Entscheidungsfähigkeit zur Lösung von Problemen mittels KI oder klassischer SW-Entwicklung

Teilnehmer:innen können entscheiden und erklären, ob und warum ein Problem mittels KI oder klassischer SW-Entwicklung zu lösen ist.

[[LZ-1-8]]
==== LZ 1-8: Rollen und deren Aufgaben im Kontext von KI

Die Teilnehmer:innen kennen typische Rollen und deren Aufgaben in diesen Kontexten. Die Rollen umfassen insbesondere:

* Data Scientist
* Data Analyst
* Data Engineer
* Machine Learning Engineer
* MLOps Engineer
* AI Architect
* Data Architect
* Business Intelligence (BI) Developer
* Data Governance Specialist
* ML-Researcher

[[LZ-1-9]]
==== LZ 1-9: Zusammenarbeit der Rollen im Team (Team Topologies für ML-Teams)

Die Teilnehmer:innen wissen, wie diese Rollen im Team zusammenarbeiten könnten (Team Topologies für ML-Teams).

[[LZ-1-10]]
==== LZ 1-10: Identifikation und Priorisierung von KI Anwendungsfällen

Die Teilnehmer:innen können KI Anwendungsfälle identifizieren und priorisieren.

[[LZ-1-11]]
==== LZ 1-11: KI Stärken und Grenzen

Die Teilnehmer:innen verstehen die Stärken und die Grenzen von KI und kennen die sog. "Jagged Technological Frontier".

[[LZ-1-12]]
==== LZ 1-12: Kennen Productivity J-Curve Konzept in Verbindung mit KI-Technologie (Dieses Phänomen hilft zu verstehen, warum Unternehmen bei der Implementierung von KI zunächst einen Produktivitätsrückgang verzeichnen können, dem bei der weiteren Entwicklung aber Produktivitätsgewinne folgen können.).

// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: The is the first learning goal, in category xy
tbd.
// end::EN[]
