=== {learning-goals}

// tag::DE[]

[[LZ-1-1]]
==== LZ 1-1: Künstliche Intelligenz und Machine Learning, Data Science, Deep Learning, Generative KI einordnen können

Die Teilnehmer:innen wissen, wie man Künstliche Intelligenz definiert und wie Machine Learning, Data Science, Deep Learning, Generative KI darin eingeordnet werden.

[[LZ-1-2]]
==== LZ 1-2: Typische allgemeine Anwendungsfälle für KI spezifizieren

Die Teilnehmer:innen wissen, wie typische allgemeine Anwendungsfälle für KI spezifiziert werden können. Dies umfasst Anwendungsfälle für z.{nbsp}B. Bilderkennung & -erzeugung, Sprachverarbeitung, Vorhersagen, Personalisierung und Anomalieerkennung.

[[LZ-1-3]]
==== LZ 1-3: Einsatzmöglichkeiten in verschiedenen Branchen und Endnutzeranwendungen kennen

Die Teilnehmer:innen kennen die möglichen Einsatzmöglichkeiten in verschiedenen Branchen, z.{nbsp}B. Marketing, Medizin, Robotik und Content-Creation. Darüber hinaus überblicken sie die Einsatzmöglichkeiten in Endnutzeranwendungen von KI. Darunter fallen z.{nbsp}B. Sprachassistenten (Chatbots) und Empfehlungssysteme (Recommender Engine).


[[LZ-1-4]]
==== LZ 1-4: Risiken bei der Anwendung von KI identifizieren

Die Teilnehmer:innen können Risiken, die bei der Anwendung von KI auftreten, identifizieren. Das können beispielsweise folgende Risiken sein:

* Halluzinationen
* Bias
* (un-)Fairness
* gesellschaftlichen Risiken wie Deepfakes, AI-enabled Cyberattacks, Safety Risks in Critical Systems, Social Manipulation, Intellectual Property Issues usw.



[[LZ-1-5]]
==== LZ 1-5: Unterschiede zu traditioneller Software verstehen

Die Teilnehmer:innen verstehen die Unterschiede von KI-Systemen zu traditioneller Software:

* Datengetrieben (bei ML) – Daten-zentrierte statt Code-zentrierte Entwicklung
* Probabilistische Ergebnisse (Non-deterministic behavior)
* Statistische Validierung
* Experimentelles Design: Unterstützung für schnelle Iteration und Testen von Modellen.
* Modellkomplexität und Interpretierbarkeit: ML-Modelle, insbesondere Deep-Learning-Modelle, können äußerst komplex sein. Der „Black-Box“-Charakter erschwert die Interpretierbarkeit und Erklärbarkeit.
* Debugging und Tests sind aufgrund des Nichtdeterminismus komplexer.
* Model Decay: Continuous monitoring und Retraining sind notwendig, um die Leistung der Modelle aufrechtzuerhalten.
* KI-spezifische Regulatorik von Branchen und auf EU-Ebene müssen berücksichtigt werden.
* Interoperabilität: Nahtlose Integration in bestehende Systeme und Technologiestacks.

[[LZ-1-6]]
==== LZ 1-6: Lösung von Problemen mittels KI oder klassischer SW-Entwicklung entscheiden

Teilnehmer:innen können entscheiden und erklären, ob und warum ein Problem mittels KI oder klassischer SW-Entwicklung zu lösen ist.

[[LZ-1-7]]
==== LZ 1-7: Rollen und deren Aufgaben sowie ihre Zusammenarbeit im Kontext von KI kennen

Die Teilnehmer:innen kennen typische Rollen und deren Aufgaben in diesen Kontexten. Die Rollen umfassen insbesondere:

Data Scientist, Data Analyst, Data Engineer, Machine Learning Engineer, MLOps Engineer, AI Architect,
Data Architect, Business Intelligence (BI) Developer, Data Governance Specialist und ML-Researcher.

Die Teilnehmer:innen wissen darüber hinaus, wie diese Rollen im Team zusammenarbeiten könnten (Team Topologies für ML-Teams).


[[LZ-1-8]]
==== LZ 1-8: KI Anwendungsfällen identifizieren und priorisieren

Die Teilnehmer:innen können KI Anwendungsfälle identifizieren und priorisieren.

[[LZ-1-9]]
==== LZ 1-9: Stärken und Grenzen von KI kennen

Die Teilnehmer:innen verstehen die Stärken und die Grenzen von KI und kennen die sog. "Jagged Technological Frontier".

[[LZ-1-10]]
==== LZ 1-10: Konzept der Productivity J-Curve in Verbindung mit KI-Technologie kennen

Dieses Phänomen hilft zu verstehen, warum Unternehmen bei der Implementierung von KI zunächst einen Produktivitätsrückgang verzeichnen können, dem bei der weiteren Entwicklung aber Produktivitätsgewinne folgen können.


// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Being able to classify artificial intelligence and machine learning, data science, deep learning, generative AI

The participants know how to define artificial intelligence and how machine learning, data science, deep learning, generative AI are classified within it.

[[LG-1-2]]
==== LG 1-2: Specifying typical general use cases for AI

The participants know how to specify typical general use cases for AI. This includes use cases for e.g. image recognition & generation, speech processing, predictions, personalization and anomaly detection.

[[LG-1-3]]
==== LG 1-3: Knowing possible uses in different industries and end-user applications

The participants know the possible uses in different industries, e.g. marketing, medicine, robotics and content creation. In addition, they have an overview of the possible uses of AI in end-user applications. These include, for example, voice assistants (chatbots) and recommendation systems (recommender engines).

[[LG-1-4]]
==== LG 1-4: Identify risks when using AI

The participants can identify risks that arise when using AI. These can be, for example, the following risks:

* Hallucinations
* Bias
* (un-)fairness
* social risks such as deepfakes, AI-enabled cyberattacks, safety risks in critical systems, social manipulation, intellectual property issues, etc.

[[LG-1-5]]
==== LG 1-5: Understanding differences to traditional software

The participants understand the differences between AI systems and traditional software:

* Data-driven (in ML) – data-centric instead of code-centric development
* Probabilistic results (non-deterministic behavior)
* Statistical validation
* Experimental design: support for rapid iteration and testing of models.

* Model complexity and interpretability: ML models, especially deep learning models, can be extremely complex. The "black box" character makes interpretability and explainability more difficult.
* Debugging and testing are more complex due to non-determinism.
* Model decay: Continuous monitoring and retraining are necessary to maintain the performance of the models.

* AI-specific regulations of industries and at EU level must be taken into account.

* Interoperability: Seamless integration into existing systems and technology stacks.

[[LG-1-6]]
==== LG 1-6: Decide whether to solve problems using AI or classic software development

Participants can decide and explain whether and why a problem should be solved using AI or classic software development.

[[LG-1-7]]
==== LG 1-7: Know roles and their tasks as well as their collaboration in the context of AI

The participants know typical roles and their tasks in these contexts. The roles include in particular:

Data Scientist, Data Analyst, Data Engineer, Machine Learning Engineer, MLOps Engineer, AI Architect,
Data Architect, Business Intelligence (BI) Developer, Data Governance Specialist and ML Researcher.

Participants also know how these roles could work together in a team (team topologies for ML teams).

[[LG-1-8]]
==== LG 1-8: Identify and prioritize AI use cases

Participants can identify and prioritize AI use cases.

[[LG-1-9]]
==== LG 1-9: Know the strengths and limitations of AI

Participants understand the strengths and limitations of AI and know the so-called "Jagged Technological Frontier".

[[LG-1-10]]
==== LG 1-10: Know the concept of the productivity J-curve in connection with AI technology

This phenomenon helps to understand why companies can initially experience a decline in productivity when implementing AI, but this can be followed by productivity gains as they develop further.


// end::EN[]
