= https://isaqb.org[iSAQB^(R)^] Advanced Level curriculum Software Architecture for AI Systems

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-swarc4ai/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-swarc4ai/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-swarc4ai.svg["Contributors",link="https://github.com/isaqb-org/curriculum-swarc4ai/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-swarc4ai.svg["Issues",link="https://github.com/isaqb-org/curriculum-swarc4ai/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-swarc4ai.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-swarc4ai/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the iSAQB^(R)^ Advanced Level curriculum Software Architecture for AI Systems.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to use this template

. Clone the repository - including all submodules:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-swarc4ai.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-swarc4ai.git --recursive
----
--

== How to build the documents

Prerequisite: You need a Java 17 (or higher) JDK installed.
Build the project with http://www.gradle.com[Gradle] (you need a locally installed JDK 17 or higher) via `./gradlew`.

== Maintainers

This repository is currently maintained by the curators of the SWARC4AI curriculum.
It was forked from https://github.com/isaqb-org/curriculum-swarc4ai,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
