// tag::DE[]
=== Was können Absolventen des Advanced Level (CPSA-A)?
CPSA-A-Absolventen können:

- eigenständig und methodisch fundiert mittlere bis große IT-Systeme entwerfen
- in IT-Systemen mittlerer bis hoher Kritikalität technische und inhaltliche Verantwortung übernehmen
- Maßnahmen zur Erreichung von Qualitätsanforderungen konzeptionieren, entwerfen und dokumentieren sowie Entwicklungsteams bei der Umsetzung dieser Maßnahmen begleiten
- architekturrelevante Kommunikation in mittleren bis großen Entwicklungsteams steuern und durchführen

// end::DE[]

// tag::EN[]
=== What are Advanced Level (CPSA-A) graduates qualified for?
CPSA-A graduates can:

-	design medium-sized to large IT systems independently and methodically
-	assume technical and content-related responsibility in IT systems of medium to high criticality
-	Conceptualize, design and document measures to achieve quality requirements and support development teams in the implementation of these measures
-	Manage and carry out architecture-related communication in medium to large development teams

// end::EN[]

