=== {learning-goals}

// tag::DE[]

[[LZ-6-1]]
==== LZ 6-1: Integrationsebenen von KI überblicken

Die Teilnehmer:innen kennen verschiedene Integrationsebenen von KI. Dazu gehören die folgenden Ebenen:

* Anwendungen (z.{nbsp}B. Coding Assistenten)
* AI-Engineering (z.{nbsp}B. Prompt Engineering)
* ML-Modellentwicklung (z.{nbsp}B. pytorch)
* ML-Infrastruktur (z.{nbsp}B. Vektor-DBs).


[[LZ-6-2]]
==== LZ 6-2: Bibliotheken, Schnittstellen und Tools zur Integration von KI-Modellen kennen

Die Teilnehmer:innen kennen einige Beispiele von verbreiteten Bibliotheken, Schnittstellen und Tools zur Integration von KI-Modellen.

[[LZ-6-3]]
==== LZ 6-3: KI-Systeme in die Gesamtarchitektur einer IT-Landschaft integrieren

Die Teilnehmer:innen kennen Möglichkeiten, KI-Systeme in IT-Landschaften auf strategischer Ebene zu integrieren. Beispielsweise
können sie das strategische Design von DDD (insbesondere Context Maps) einsetzen,
um die Art und den Grad der Integration von KI-Systemen zu bestimmen und zu dokumentieren.

[[LZ-6-4]]
==== LZ 6-4: Relevante Qualitätsmerkmale für KI-Systeme überblicken

Die Teilnehmer:innen verstehen die Qualitätsmerkmale, die für KI-Systeme besonders relevant sind. Dazu gehören insbesondere die folgenden Qualitätsmerkmale:

* Verlässlichkeit
* Skalierbarkeit
* Effizienz
* Sicherheit
* Wartbarkeit
* Interpretierbarkeit

[[LZ-6-5]]
==== LZ 6-5: [OPTIONAL] Evaluations-Frameworks für KI-Systeme kennen

Die Teilnehmer:innen kennen gängige Evaluations-Frameworks wie beispielsweise LangSmith oder LangFuse, um mit Unbestimmtheit und Fehlern in KI-Systemen umzugehen.


[[LZ-6-6]]
==== LZ 6-6: [OPTIONAL] Fallbeispiel mit einer ausgedachten Fachlichkeit diskutieren

Die Teilnehmer:innen üben und diskutieren anhand eines Fallbeispiels mit einer ausgedachten Fachlichkeit, Integrationsoptionen für KI in eine bestehende Software-Landschaft abzuwägen.

[[LZ-6-7]]
==== LZ 6-7: Generative KI grundlegend verstehen

Die Teilnehmer:innen haben ein grundlegendes Verständnis von generativer KI wie beispielsweise LLMs und Stable Diffusion.

[[LZ-6-8]]
==== LZ 6-8: Funktionsweise von LLMs verstehen

Die Teilnehmer:innen verstehen die Funktionsweise von LLMs und können die zugehörige Begriffswelteinordnen: Token, Embedding, RNN, Transformer, Attention.

[[LZ-6-9]]
==== LZ 6-9: Bekannte Patterns bei der Nutzung von LLMs kennen

Die Teilnehmer:innen kennen bekannte Patterns bei der Nutzung von LLMs. Dies umfasst die folgenden Patterns:
* RAG und Retrieval-Strategien
* Function Calling
* Finetuning
* Assistenten
* Agenten

[[LZ-6-10]]
==== LZ 6-10: Use-Cases für RAG (Retrieval-Augmented Generation) kennen

Die Teilnehmer:innen kennen typische Use-Cases für RAG wie beispielsweise „Talk to your documents/database/API“.

[[LZ-6-11]]
==== LZ 6-11: Ausgewählte RAG-Techniken kennen und verstehen

Die Teilnehmer:innen kennen eine Auswahl der gängigen RAG-Techniken wie beispielsweise:

* Simple RAG
* Context Enrichment Techniques
* Fusion Retrieval
* Intelligent Reranking
* Query Transformations
* Adaptive Retrieval
* Iterative Retrieval
* Ensemble Retrieval
* Knowledge Graph Integration

[[LZ-6-12]]
==== LZ 6-12: Arten von Prompt Engineering kennen

Die Teilnehmer:innen kennen verschiedene Arten von Prompt Engineering, wie beispielsweise

* Few-Shot-Learning
* Chain-of-Thought
* Role-Playing

sowie allgemeine Best Practices für das Prompting.

[[LZ-6-13]]
==== LZ 6-13: Agentic Workflows überblicken

Die Teilnehmer:innen wissen, was Agentic Workflows sind und kennen die Begriffe Reflexion, Werkzeugnutzung, Planung und Multi-Agenten-Kollaboration.

[[LZ-6-14]]
==== LZ 6-14: Eine Auswahl von Design Patterns für Generative KI-Systeme kennen

Die Teilnehmer:innen wissen welche Design Patterns für Generative KI-Systeme existieren. Sie kennen eine Auswahl der folgenden Patterns:

* AI Query Router [Simple Router; Ranking-based Router; Learning-based Router
* Layered Caching Strategy Leading to Fine-Tuning
* Multiplexing AI Agents
* Fine-Tuning LLMs for Multiple Tasks
* Blending Rules-Based and Generative Approaches
* Utilizing Knowledge Graphs with LLMs
* Swarm of Generative AI Agents
* Modular Monolith LLM Approach with Composability
* Memory Cognition for LLMs
* Red and Blue Team Dual-Model Evaluation

[[LZ-6-15]]
==== LZ 6-15: Techniken zur Evaluation von LLM-Anwendungen kennen

Die Teilnehmer:innen kennen mehrere Techniken zur Evaluation von LLM-Anwendungen. Dies können beispielsweise die folgenden Techniken sein:

* Scoring
* Human Feedback
* Comparative Evaluation
* Model Based Evaluation

[[LZ-6-16]]
==== LZ 6-16: Bekannte LLMs und Auswahlkriterien überblicken

Die Teilnehmer:innen kennen bekannte LLMs wie beispielsweise GPT, Claude, Gemini, Llama, Mistral oder Luminous, und Auswahlkriterien für ein geeignetes LLM.


[[LZ-6-17]]
==== LZ 6-17: Bedeutung von Cost Management für GenAI Applikationen verstehen

Die Teilnehmer:innen verstehen die Bedeutung von Cost Management für GenAI Applikationen.

[[LZ-6-18]]
==== LZ 6-18: Beispiele von verbreiteten Bibliotheken, Schnittstellen und Tools im Zusammenhang mit LLM-Anwendungen nennen

Die Teilnehmer:innen kennen einige Beispiele von verbreiteten Bibliotheken, Schnittstellen und Tools im Zusammenhang
mit LLM-Anwendungen wie beispielsweise OpenAI-API oder LangChain.

[[LZ-6-19]]
==== LZ 6-19: [OPTIONAL] Agentic AI Software Architekturen, AI Agent Architekturkomponenten und Typen von AI Agentarchitekturen kennen

Die Teilnehmer:innen kennen Agentic AI Software Architekturen, AI Agent Architekturkomponenten, Typen von AI Agentarchitekturen.

// end::DE[]

// tag::EN[]

[[LG-6-1]]
==== LG 6-1: Overview of integration levels of AI

Participants are familiar with the various levels of AI integration. These include the following levels:

- Applications (e.g. coding assistants)
- AI engineering (e.g. prompt engineering)
- ML model development (e.g. pytorch)
- ML infrastructure (e.g. vector DBs).

[[LG-6-2]]
==== LG 6-2: Know libraries, interfaces and tools for the integration of AI models

The participants know some examples of common libraries, interfaces and tools for the integration of AI models.


[[LG-6-3]]
==== LG 6-3: Integrate AI systems into the overall architecture of an IT landscape

Participants know how integrate AI systems into IT landscapes at a strategic level. For example, they can use the strategic design of DDD (especially context maps) to determine and document the type and degree of integration of AI systems.

[[LG-6-4]]
==== LG 6-4: Overview of relevant quality features for AI systems

The participants understand the quality characteristics that are particularly relevant for AI systems. This includes the following quality characteristics in particular:

- Reliability
- Scalability
- Efficiency
- Security
- Maintainability
- Interpretability


[[LG-6-5]]
==== LG 6-5: [OPTIONAL] Know evaluation frameworks for AI systems

Participants are familiar with common evaluation frameworks such as LangSmith or LangFuse to deal with indeterminacy and errors in AI systems.

[[LG-6-6]]
==== LG 6-6: [OPTIONAL] Discuss a case study with an imaginary professionalism

Participants will practise and discuss a case study with an imaginary technicality to weigh up integration options for AI into an existing software landscape.

[[LG-6-7]]
==== LG 6-7: Fundamental understanding of generative AI

The participants have a basic understanding of generative AI such as LLMs and stable diffusion.

[[LG-6-8]]
==== LG 6-8: Understanding how LLMs work

Participants understand how LLMs work and can categorize the associated terminology: Token, Embedding, RNN, Transformer, Attention.

[[LG-6-9]]
==== LG 6-9: Understand known patterns in the use of LLMs

The participants understand known patterns for the use of LLMs. This includes the following patterns:

- RAG and retrieval strategies
- Function calling
- Finetuning
- Assistants
- Agents

[[LG-6-10]]
==== LG 6-10: Knowing use cases for RAG (Retrieval-Augmented Generation)

The participants know typical use cases for RAG such as "Talk to your documents/database/API".

[[LG-6-11]]
==== LG 6-11: Knowing and understanding selected RAG techniques

The participants know a selection of common RAG techniques such as:

- Simple RAG
- Context Enrichment Techniques
- Fusion Retrieval
- Intelligent Reranking
- Query Transformations
- Adaptive Retrieval
- Iterative retrieval
- Ensemble Retrieval
- Knowledge Graph Integration


[[LG-6-12]]
==== LG 6-12: Know types of prompt engineering

The participants know different types of prompt engineering, such as

- Few-Shot-Learning
- Chain-of-Thought
- Role-Playing

as well as general best practices for prompting.


[[LG-6-13]]
==== LG 6-13: Overview of agentic workflows

Participants know what agentic workflows are and are familiar with the terms reflection, tool usage, planning and multi-agent collaboration.

[[LG-6-14]]
==== LG 6-14: Know a selection of design patterns for generative AI systems

The participants know which design patterns exist for generative AI systems. They know a selection of the following patterns:

- AI Query Router [Simple Router; Ranking-based Router; Learning-based Router
- Layered Caching Strategy Leading to Fine-Tuning
- Multiplexing AI Agents
- Fine-Tuning LLMs for Multiple Tasks
- Blending Rules-Based and Generative Approaches
- Utilizing Knowledge Graphs with LLMs
- Swarm of Generative AI Agents
- Modular Monolith LLM Approach with Composability
- Memory Cognition for LLMs
- Red and Blue Team Dual-Model Evaluation


[[LG-6-15]]
==== LG 6-15: Know techniques for evaluating LLM applications

The participants know several techniques for evaluating LLM applications. These can be, for example, the following techniques:

- Scoring
- Human feedback
- Comparative Evaluation
- Model Based Evaluation


[[LG-6-16]]
==== LG 6-16: Overview of known LLMs and selection criteria

The participants are familiar with well-known LLMs such as GPT, Claude, Gemini, Llama, Mistral or Luminous, and the selection criteria for a suitable LLM.

[[LG-6-17]]
==== LG 6-17: Understanding the importance of cost management for GenAI applications

The participants understand the importance of cost management for GenAI applications.

[[LG-6-18]]
==== LG 6-18: Give examples of common libraries, interfaces and tools related to LLM applications

The participants know some examples of common libraries, interfaces and tools in connection with LLM applications such as OpenAI-API or LangChain.

[[LG-6-19]]
==== LG 6-19: [OPTIONAL] Know agentic AI software architectures, AI agent architecture components and types of AI agent architectures

The participants know agentic AI software architectures, AI agent architecture components, types of AI agent architectures.



// end::EN[]
