=== {learning-goals}

// tag::DE[]

[[LZ-6-1]]
==== LZ 6-1: Integrationsebenen von KI überblicken

Die Teilnehmer:innen kennen verschiedene Integrationsebenen von KI. Dazu gehören die folgenden Ebenen:

* Anwendungen (z.{nbsp}B. Coding Assistenten)
* AI-Engineering (z.{nbsp}B. Prompt Engineering)
* ML-Modellentwicklung (z.{nbsp}B. pytorch)
* ML-Infrastruktur (z.{nbsp}B. Vektor-DBs).


[[LZ-6-2]]
==== LZ 6-2: Bibliotheken, Schnittstellen und Tools zur Integration von KI-Modellen kennen

Die Teilnehmer:innen kennen einige Beispiele von verbreiteten Bibliotheken, Schnittstellen und Tools zur Integration von KI-Modellen.

[[LZ-6-3]]
==== LZ 6-3: KI-Systeme in die Gesamtarchitektur einer IT-Landschaft integrieren

Die Teilnehmer:innen kennen Möglichkeiten, KI-Systeme in IT-Landschaften auf strategischer Ebene zu integrieren. Beispielsweise
können sie das strategische Design von DDD (insbesondere Context Maps) einsetzen,
um die Art und den Grad der Integration von KI-Systemen zu bestimmen und zu dokumentieren.

[[LZ-6-4]]
==== LZ 6-4: Relevante Qualitätsmerkmale für KI-Systeme überblicken

Die Teilnehmer:innen verstehen die Qualitätsmerkmale, die für KI-Systeme besonders relevant sind. Dazu gehören insbesondere die folgenden Qualitätsmerkmale:

* Verlässlichkeit
* Skalierbarkeit
* Effizienz
* Sicherheit
* Wartbarkeit
* Interpretierbarkeit

[[LZ-6-5]]
==== LZ 6-5: [OPTIONAL] Evaluations-Frameworks für KI-Systeme kennen

Die Teilnehmer:innen kennen gängige Evaluations-Frameworks wie beispielsweise LangSmith oder LangFuse, um mit Unbestimmtheit und Fehlern in KI-Systemen umzugehen.


[[LZ-6-6]]
==== LZ 6-6: [OPTIONAL] Fallbeispiel mit einer ausgedachten Fachlichkeit diskutieren

Die Teilnehmer:innen üben und diskutieren anhand eines Fallbeispiels mit einer ausgedachten Fachlichkeit, Integrationsoptionen für KI in eine bestehende Software-Landschaft abzuwägen.

[[LZ-6-7]]
==== LZ 6-7: Generative KI grundlegend verstehen

Die Teilnehmer:innen haben ein grundlegendes Verständnis von generativer KI wie beispielsweise LLMs und Stable Diffusion.

[[LZ-6-8]]
==== LZ 6-8: Funktionsweise von LLMs verstehen

Die Teilnehmer:innen verstehen die Funktionsweise von LLMs und können die zugehörige Begriffswelteinordnen: Token, Embedding, RNN, Transformer, Attention.

[[LZ-6-9]]
==== LZ 6-9: Bekannte Patterns bei der Nutzung von LLMs kennen

Die Teilnehmer:innen kennen bekannte Patterns bei der Nutzung von LLMs. Dies umfasst die folgenden Patterns:
* RAG und Retrieval-Strategien
* Function Calling
* Finetuning
* Assistenten
* Agenten

[[LZ-6-10]]
==== LZ 6-10: Use-Cases für RAG (Retrieval-Augmented Generation) kennen

Die Teilnehmer:innen kennen typische Use-Cases für RAG wie beispielsweise „Talk to your documents/database/API“.

[[LZ-6-11]]
==== LZ 6-11: Ausgewählte RAG-Techniken kennen und verstehen

Die Teilnehmer:innen kennen eine Auswahl der gängigen RAG-Techniken wie beispielsweise:

* Simple RAG
* Context Enrichment Techniques
* Fusion Retrieval
* Intelligent Reranking
* Query Transformations
* Adaptive Retrieval
* Iterative Retrieval
* Ensemble Retrieval
* Knowledge Graph Integration

[[LZ-6-12]]
==== LZ 6-12: Arten von Prompt Engineering kennen

Die Teilnehmer:innen kennen verschiedene Arten von Prompt Engineering, wie beispielsweise

* Few-Shot-Learning
* Chain-of-Thought
* Role-Playing

sowie allgemeine Best Practices für das Prompting.

[[LZ-6-13]]
==== LZ 6-13: Agentic Workflows überblicken

Die Teilnehmer:innen wissen, was Agentic Workflows sind und kennen die Begriffe Reflexion, Werkzeugnutzung, Planung und Multi-Agenten-Kollaboration.

[[LZ-6-14]]
==== LZ 6-14: Eine Auswahl von Design Patterns für Generative KI-Systeme kennen

Die Teilnehmer:innen wissen welche Design Patterns für Generative KI-Systeme existieren. Sie kennen eine Auswahl der folgenden Patterns:

* AI Query Router [Simple Router; Ranking-based Router; Learning-based Router
* Layered Caching Strategy Leading to Fine-Tuning
* Multiplexing AI Agents
* Fine-Tuning LLMs for Multiple Tasks
* Blending Rules-Based and Generative Approaches
* Utilizing Knowledge Graphs with LLMs
* Swarm of Generative AI Agents
* Modular Monolith LLM Approach with Composability
* Memory Cognition for LLMs
* Red and Blue Team Dual-Model Evaluation

[[LZ-6-15]]
==== LZ 6-15: Techniken zur Evaluation von LLM-Anwendungen kennen

Die Teilnehmer:innen kennen mehrere Techniken zur Evaluation von LLM-Anwendungen. Dies können beispielsweise die folgenden Techniken sein:

* Scoring
* Human Feedback
* Comparative Evaluation
* Model Based Evaluation

[[LZ-6-16]]
==== LZ 6-16: Bekannte LLMs und Auswahlkriterien überblicken

Die Teilnehmer:innen kennen bekannte LLMs wie beispielsweise GPT, Claude, Gemini, Llama, Mistral oder Luminous, und Auswahlkriterien für ein geeignetes LLM.


[[LZ-6-17]]
==== LZ 6-17: Bedeutung von Cost Management für GenAI Applikationen verstehen

Die Teilnehmer:innen verstehen die Bedeutung von Cost Management für GenAI Applikationen.

[[LZ-6-18]]
==== LZ 6-18: Beispiele von verbreiteten Bibliotheken, Schnittstellen und Tools im Zusammenhang mit LLM-Anwendungen nennen

Die Teilnehmer:innen kennen einige Beispiele von verbreiteten Bibliotheken, Schnittstellen und Tools im Zusammenhang
mit LLM-Anwendungen wie beispielsweise OpenAI-API oder LangChain.

[[LZ-6-19]]
==== LZ 6-19: [OPTIONAL] Agentic AI Software Architekturen, AI Agent Architekturkomponenten und Typen von AI Agentarchitekturen kennen

Die Teilnehmer:innen kennen Agentic AI Software Architekturen, AI Agent Architekturkomponenten, Typen von AI Agentarchitekturen.

// end::DE[]

// tag::EN[]

[[LG-6-1]]
==== LG 6-1: Overview of AI integration levels

The participants are familiar with various AI integration levels. These include the following levels:

* Applications (e.g. coding assistants)
* AI engineering (e.g. prompt engineering)
* ML model development (e.g. pytorch)
* ML infrastructure (e.g. Vector DBs).

[[LG-6-2]]
==== LG 6-2: Know libraries, interfaces and tools for integrating AI models

The participants are familiar with some examples of common libraries, interfaces and tools for integrating AI models.

[[LG-6-3]]
==== LG 6-3: Integrating AI systems into the overall architecture of an IT-Landscape

The participants know ways to integrate AI systems into IT landscapes at a strategic level. For example, they can use the strategic design of DDD (especially context maps) to determine and document the type and degree of integration of AI systems.

[[LG-6-4]]
==== LG 6-4: Overview of relevant quality characteristics for AI-Systems

The participants understand the quality characteristics that are particularly relevant for AI-Systems. These include in particular the following quality characteristics:

* Reliability
* Scalability
* Efficiency
* Security
* Maintainability
* Interpretability

[[LG-6-5]]
==== LG 6-5: [OPTIONAL] Know evaluation frameworks for AI systems

The participants are familiar with common evaluation frameworks such as LangSmith or LangFuse to deal with uncertainty and errors in AI-Systems.

[[LG-6-6]]
==== LG 6-6: [OPTIONAL] Discuss a case study with an imaginary technical aspect

The participants practice and discuss weighing up integration options for AI in an existing software landscape using a case study with an imaginary technical aspect.

[[LG-6-7]]
==== LG 6-7: Basic understanding of generative AI

The participants have a basic understanding of generative AI such as LLMs and Stable Diffusion.

[[LG-6-8]]
==== LG 6-8: Understanding how LLMs work

The participants understand how LLMs work and can classify the associated terminology: Token, Embedding, RNN, Transformer, Attention.

[[LG-6-9]]
==== LG 6-9: Knowing familiar patterns when using LLMs

The participants know familiar patterns when using LLMs. This includes the following patterns:
* RAG and Retrieval Strategies
* Function Calling
* Fine-Tuning
* Assistants
* Agents

[[LG-6-10]]
==== LG 6-10: Know use cases for RAG (Retrieval-Augmented Generation)

The participants know typical use cases for RAG such as “Talk to your Documents/Database/API”.

[[LG-6-11]]
==== LG 6-11: Know and understand selected RAG techniques

The participants know a selection of the common RAG techniques such as:

* Simple RAG
* Context Enrichment Techniques
* Fusion Retrieval
* Intelligent Reranking
* Query Transformations
* Adaptive Retrieval
* Iterative Retrieval
* Ensemble Retrieval
* Knowledge Graph Integration

[[LG-6-12]]
==== LG 6-12: Know types of Prompt-Engineering

The participants know different types of prompt engineering, such as:

* Few-shot Learning
* Chain-of-Thought
* Role-Playing

as well as general best practices for prompting.

[[LG-6-13]]
==== LZ G-13: Overview of Agentic-Workflows

The participants know what Agentic-Workflows are and are familiar with the terms reflection, tool usage, planning and multi-agent collaboration.

[[LG-6-14]]
==== LG 6-14: Know a selection of design patterns for Generative AI-Systems

The participants know which design patterns exist for generative AI-Systems. They know a selection of the following patterns:

* AI Query Router [Simple Router; Ranking-based Router; Learning-based Router]
* Layered Caching Strategy Leading to Fine-Tuning
* Multiplexing AI-Agents
* Fine-Tuning LLMs for Multiple Tasks
* Blending Rules-Based and Generative Approaches
* Utilizing Knowledge Graphs with LLMs
* Swarm of Generative AI Agents
* Modular Monolith LLM Approach with Composability
* Memory Cognition for LLMs
* Red and Blue Team Dual-Model Evaluation

[[LG-6-15]]
==== LG 6-15: Know techniques for evaluating LLM Applications

The participants know several techniques for evaluating LLM Applications. These can be, for example, the following techniques:

* Scoring
* Human Feedback
* Comparative Evaluation
* Model Based Evaluation

[[LG-6-16]]
==== LG 6-16: Overview of well-known LLMs and selection Criteria

The participants know well-known LLMs such as GPT, Claude, Gemini, Llama, Mistral or Luminous, and selection Criteria for a suitable LLM.

[[LG-6-17]]
==== LG 6-17: Understanding the importance of cost management for GenAI Applications

The participants understand the importance of cost management for GenAI Applications.

[[LG-6-18]]
==== LG 6-18: Give examples of common libraries, interfaces and tools related to LLM applications

The participants know some examples of common libraries, interfaces and tools related to LLM applications such as OpenAI API or LangChain.

[[LG-6-19]]
==== LG 6-19: [OPTIONAL] Know Agentic AI Software Architectures, AI Agent Architecture Components and types of AI Agent Architectures

The participants know Agentic AI software architectures, AI agent architecture components, types of AI agent architectures.

// end::EN[]
