=== {learning-goals}

// tag::DE[]


[[LZ-3-1]]
==== LZ 3-1: Life-Cycle eines Machine-Learning- bzw. Data-Science-Projekts verstehen

Die Teilnehmer:innen haben ein Verständnis für den Life-Cycle eines Machine-Learning- bzw. Data-Science-Projekts. Dabei kennen sie insbesondere die folgenden Phasen:

* Exploratory Data Analysis
* Data Cleansing und Aufbereitung
* Feature Engineering
* Modell Training und Auswahl
* POC
* Deployment
* Maintenance

Die Teilnehmer:innen kennen typische Vorgehensmodelle für die Softwareentwicklung von KI-Systemen. Dies sind beispielsweise

* CRISP-ML(Q)
* Team Data Science Process
* GenAI Life Cycle.

[[LZ-3-2]]
==== LZ 3-2: Datenarten und Anforderungen an Daten sowie typische ML-Problemstellungen und deren Anforderungen verstehen

Die Teilnehmer:innen kennen verschiedene Arten von Daten sowie typische ML-Probleme und Anwendungsfälle für die Nutzung der Daten aus den Bereichen:

* Supervised Learning
* Unsupervised Learning
* Reinforcement Learning

und verstehen, welche Anforderungen diese haben können, z.B.:

* Vorhandensein von korrekten Labels verschiedener Art
* Datenumfang und -diversität
* Zeitliche oder semantische Abhängigkeiten in Datenmerkmalen
* Kodierung der Eingabedaten von ML-Modellen, z.B.:
  * One-Hot-Encodings
  * Label Encodings
  * Embeddings

Insbesondere haben die Teilnehmer:innen ein gutes Verständnis für die Notwendigkeit von Validierung und Kenntnis der typischen Datenaufteilung in Trainings-, Validierungs- und Testdaten.


[[LZ-3-3]]
==== LZ 3-3: Geeignete Architektur- und Design-Patterns für KI-Systeme auswählen, gegeneinander abwägen und anhand von Qualitätsanforderungen begründen.

Die Teilnehmer:innen wissen, welche Design Patterns für KI-Systeme existieren und wie man passende Patterns auswählt. Das betrifft die folgenden Design Patterns:

* ML Systems Topology Patterns
* Pipeline Architecture Patterns
* Model Training Pattern
* Model Serving Patterns
* Model Deployment Patterns

Insbesondere kennen die Teilnehmer:innen Transfer-Learning bzw. Fine-Tuning als Möglichkeit, um die vortrainierten Basismodelle auf bestehende Anwendungsfälle zu adoptieren.


[[LZ-3-4]]
==== LZ 3-4: Metriken zur Messung der Performance von ML-Modellen kennen

Die Teilnehmer:innen kennen verschiedene Metriken zur Messung der Performance von ML-Modellen wie beispielsweise:

* Precision, Recall
* F1-Score
* Accuracy

und wissen, wie man Bewertungskriterien zur Leistungsbeurteilung festlegt.

[[LZ-3-5]]
==== LZ 3-5: KI-Komponenten über geeignete Integrationsmuster, Schnittstellen und Entkopplungsmechanismen in bestehende Systeme und Domänenarchitekturen integrieren.

Die Teilnehmer:innen verstehen, wie ML-Modelle in bestehende Systeme integriert werden können und kennen die Schnittstellen und Integrationspunkte.

[[LZ-3-6]]
==== LZ 3-6: Benutzerinteraktionen für KI-Systeme so gestalten, dass Unsicherheit, Erklärbarkeit, Freigaben und Human-in-the-Loop angemessen berücksichtigt werden.

Die Teilnehmer:innen wissen, wie Benutzeroberflächen gestaltet werden sollten, um effektive Interaktionen mit dem ML-System zu ermöglichen und die Benutzererfahrung zu optimieren.

[[LZ-3-7]]
==== LZ 3-7: Leistung und Skalierbarkeit von KI-Systemen analysieren und gestalten

Die Teilnehmer:innen verstehen die Bedeutung von Leistungskennzahlen wie Latenz, Durchsatz und Resourcenauslastung in KI-Systemen für Training sowie Inferenz und verstehen,
wie diese optimiert werden können.

Sie können Ursachen von Leistungs- und Skalierungsproblemen analysieren und geeignete Maßnahmen auswählen, damit KI-Systeme steigende Datenmengen, Nutzerzahlen und Anfragevolumen verarbeiten können.

[[LZ-3-8]]
==== LZ 3-8: Robustheit in KI-Systemen verstehen und Strategien zur Erhöhung der Robustheit anwenden

Die Teilnehmer:innen haben ein Verständnis davon, was Robustheit in KI-Systemen bedeutet,
und können Strategien zur Erhöhung der Robustheit in verschiedenen Anwendungskontexten anwenden.

[[LZ-3-9]]
==== LZ 3-9: Zuverlässigkeit und Verfügbarkeit von KI-Systemen einordnen

Die Teilnehmer:innen verstehen die Konzepte der Zuverlässigkeit und Verfügbarkeit und wissen, wie sie KI-Systeme bauen, die stabil und konstant verfügbar sind.

[[LZ-3-10]]
==== LZ 3-10: Maßnahmen für Reproduzierbarkeit, Auditierbarkeit und Nachvollziehbarkeit von Modellen, Datenständen, Prompts, Konfigurationen und Ergebnissen festlegen.

Die Teilnehmer:innen wissen, wie wichtig es ist, dass KI-Ergebnisse reproduzierbar und prüfbar sind, und wissen, welche Methoden zur Sicherstellung dieser Eigenschaften eingesetzt werden können.


[[LZ-3-11]]
==== LZ 3-11: Erklärbarkeit und Interpretierbarkeit in KI-Systemen einordnen

Die Teilnehmer:innen verstehen die Bedeutung von Erklärbarkeit und Interpretierbarkeit in KI-Systemen und wissen,
wie man diese sicherstellen kann, um Vertrauen und Transparenz zu fördern.

[[LZ-3-12]]
==== LZ 3-12: Fehlertoleranz in KI-Systemen kennen

Die Teilnehmer:innen kennen die Konzepte der Fehlertoleranz und können erläutern, wie KI-Systeme trotz Fehlern oder Störungen funktionsfähig bleiben.

[[LZ-3-13]]
==== LZ 3-13: Architekturentscheidungen für KI-Systeme dokumentieren.

Die Teilnehmer:innen wissen, wie man die Anwendungsfälle bzw. Aufgaben eines ML-Modells definiert und dokumentiert, wie beispielsweise die Klassifikation von Bildern oder die Erkennung von Betrug, insbesondere Trade-offs zu:
* RAG versus Fine-Tuning
* SaaS versus Self-Hosting
* Batch versus Realtime
* Zentralem versus domänenspezifischem KI-Service.


// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Understand the life cycle of a machine learning or data science project

Participants have an understanding of the life cycle of a machine learning or data science project. In particular, they are familiar with the following phases:

* Exploratory data analysis
* Data cleansing and preparation
* Feature engineering
* Model training and selection
* POC
* Deployment
* Maintenance


Participants know typical process models for the software development of AI systems. These include, for example:

* CRISP-ML(Q)
* Team Data Science Process
* GenAI Life Cycle


[[LG-3-2]]
==== LG 3-2: Understand data types and requirements as well as typical ML problems and their requirements

Participants know different types of data as well as typical ML problems and use cases involving data from the following areas:

* Supervised learning
* Unsupervised learning
* Reinforcement learning

They understand the requirements these may have, for example:

* Availability of correct labels of different types
* Data volume and diversity
* Temporal or semantic dependencies in data features
* Encoding the input data of ML models, for example:
** One-hot encodings
** Label encodings
** Embeddings


In particular, participants have a good understanding of the need for validation and of the typical division of data into training, validation, and test datasets.

[[LG-3-3]]
==== LG 3-3: Select and compare suitable architecture and design patterns for AI systems and justify the selection based on quality requirements

Participants know which design patterns exist for AI systems and how to select suitable patterns. This includes the following design patterns:

* ML systems topology patterns
* Pipeline architecture patterns
* Model training patterns
* Model serving patterns
* Model deployment patterns

In particular, participants know transfer learning and fine-tuning as ways to adapt pretrained foundation models to existing use cases.


[[LG-3-4]]
==== LG 3-4: Know metrics for measuring the performance of ML models

Participants are familiar with various metrics for measuring the performance of ML models, such as:

* Precision, recall
* F1 score
* Accuracy

and know how to define evaluation criteria for performance assessment.


[[LG-3-5]]
==== LG 3-5: Integrate AI components into existing systems and domain architectures using suitable integration patterns, interfaces, and decoupling mechanisms

Participants understand how ML models can be integrated into existing systems and are familiar with the interfaces and integration points.

[[LG-3-6]]
==== LG 3-6: Design user interactions for AI systems that appropriately account for uncertainty, explainability, approvals, and human-in-the-loop

Participants know how user interfaces should be designed to enable effective interactions with the ML system and optimize the user experience.


[[LG-3-7]]
==== LG 3-7: Analyze and design the performance and scalability of AI systems

Participants understand the importance of performance indicators such as latency, throughput, and resource utilization in AI systems for both training and inference, and understand how these can be optimized.

They can analyze the causes of performance and scalability problems and select suitable measures that enable AI systems to handle growing data volumes, numbers of users, and request volumes.


[[LG-3-8]]
==== LG 3-8: Understand robustness in AI systems and apply strategies to increase robustness

Participants have an understanding of what robustness means in AI systems and can apply strategies to increase robustness in different application contexts.


[[LG-3-9]]
==== LG 3-9: Classify the reliability and availability of AI systems

Participants understand the concepts of reliability and availability and know how to build AI systems that are stable and constantly available.


[[LG-3-10]]
==== LG 3-10: Specify measures for the reproducibility, auditability, and traceability of models, dataset versions, prompts, configurations, and results

Participants know the importance of AI results being reproducible and auditable and know which methods can be used to ensure these properties.

[[LG-3-11]]
==== LG 3-11: Classify explainability and interpretability in AI systems

Participants understand the importance of explainability and interpretability in AI systems and know how to ensure this in order to promote trust and transparency.


[[LG-3-12]]
==== LG 3-12: Know fault tolerance in AI systems

Participants are familiar with the concepts of fault tolerance and can explain how AI systems remain functional despite errors or malfunctions.

[[LG-3-13]]
==== LG 3-13: Document architectural decisions for AI systems

Participants know how to define and document the use cases or tasks of an ML model, such as image classification or fraud detection, particularly the trade-offs between:

* RAG versus fine-tuning
* SaaS versus self-hosting
* Batch versus real time
* A centralized versus a domain-specific AI service

// end::EN[]
