=== {learning-goals}

// tag::DE[]

[[LZ-4-1]]
==== LZ 4-1: Daten akquirieren und labeln

Die Teilnehmer:innen überblicken verschiedene Methoden, um Daten zu akquirieren und Daten zu labeln.

[OPTIONAL]
Die Teilnehmer:innen kennen relevante Werkzeuge fürs Daten-Labeln wie beispielsweise CVAT, Label Studio oder Amazon Mechanical Turk.

[[LZ-4-2]]
==== LZ 4-2: Quellen und Eignung öffentlich verfügbarer Datensätze hinsichtlich Qualität, Lizenz, Repräsentativität und Risiken bewerten.

Die Teilnehmer:innen können gängige Plattformen für öffentlich zugängliche Daten nennen.


[[LZ-4-4]]
==== LZ 4-4: Datenpipelines und Datenarchitekturen für KI-Systeme so entwerfen, dass Qualität, Nachvollziehbarkeit, Skalierbarkeit, Governance und Wiederverwendbarkeit unterstützt werden.

Die Teilnehmer:innen haben ein Verständnis für die Gestaltung effizienter Datenpipelines und -architekturen, die Betrachtung von Datenqualität
sowie für Speicherlösungen und deren Management. Dazu kennen die Teilnehmer:innen:

* Architekturmuster für Data-Engineering-Pipelines und ETL-Prozesse
* Wie eine effektive Datenverwaltung die Qualität und Sicherheit von Daten in KI-Anwendungen sicherstellt

[OPTIONAL]
Die Teilnehmer:innen überblicken relevante Werkzeuge für Data Engineering Pipelines wie beispielsweise Apache Spark und Flink.

[[LZ-4-5]]
==== LZ 4-5: Strategien für Datenaggregation, -bereinigung, -transformation, -anreicherung und -augmentierung kennen

Die Teilnehmer:innen kennen Strategien für Datenaggregation, -bereinigung, -transformation, -anreicherung und -augmentierung.


[[LZ-4-7]]
==== LZ 4-7: Möglichkeiten zur Speicherung der Daten kennen

Die Teilnehmer:innen kennen verschiedene Möglichkeiten zur Speicherung der Daten sowie deren Vor- und Nachteile. Zu den Möglichkeiten gehören die folgenden Technologien:

* CSV-Dateien
* Spaltenorientierte Dateien
* Relationale und Dokumentbasierte Datenbanken
* Data Warehouses
* Data Lakes
* Vektordatenbanken
* Graphdatenbanken

[[LZ-4-8]]
==== LZ 4-8: Data Products, Data Contracts und Verantwortlichkeiten in Datenarchitekturen für KI-Systeme einordnen und für robuste Schnittstellen zwischen Fachlichkeit, Datenplattform und KI-Komponenten nutzen.

Die Teilnehmer:innen kennen grundlegende Konzepte moderner Datenarchitekturen für KI-Systeme und verstehen die Rolle von Data Products, Data Contracts sowie fachlicher und technischer Verantwortlichkeiten für stabile und skalierbare Datenflüsse.


// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Acquiring and labeling data

Participants gain an overview of various methods for acquiring and labeling data.

[[LG-4-2]]
==== LG 4-2: Know common platforms for publicly accessible data
Participants can name common platforms for publicly accessible data.

[[LG-4-3]]
==== LG 4-3: Overview of relevant tools for data labeling

The participants know relevant tools for data labeling such as CVAT, Amazon Mechanical Turk.


[[LG-4-4]]
==== LG 4-4: Designing efficient data pipelines and architectures

The participants have an understanding of the design of efficient data pipelines and data architectures, and they understand how to consider data quality for storage solutions and their management.
To this end, participants are familiar with architectural patterns for data engineering pipelines and ETL processes.


[[LG-4-5]]
==== LG 4-5: Know strategies for data aggregation, cleansing, transformation, enrichment and augmentation

The participants know strategies for data aggregation, cleansing, transformation, enrichment and augmentation.


[[LG-4-6]]
==== LG 4-6: Overview of tools for data engineering pipelines

Participants will gain an overview of relevant tools for data engineering pipelines such as Apache Spark and Flink.


[[LG-4-7]]
==== LG 4-7: Know the options for storing data

Participants will be familiar with various options for storing data as well as their advantages and disadvantages. The options include the following technologies:

- CSV files
- Column-oriented files
- Relational and NoSQL databases
- Data warehouses
- Data Lakes


// end::EN[]
