// tag::DE[]
=== Was vermittelt das Modul „{curriculum-short}“?

Das Modul präsentiert den Teilnehmer:innen moderne Softwarearchitektur-Konzepte
für KI-Systeme als Mittel, um leistungsfähige, skalierbare und integrierbare KI-
Lösungen zu gestalten. Am Ende des Moduls kennen die Teilnehmer:innen die
wesentlichen Prinzipien der Softwarearchitektur für KI-Systeme und können diese
bei Entwurf und Implementierung von Machine Learning und Generative KI-
Systemen anwenden. Mit Hilfe der vermittelten
Modellierungstechniken und Architekturwerkzeuge können sie KI-Komponenten
nahtlos in bestehende Softwaresysteme integrieren. Die Schulung umfasst sowohl
Machine Learning Systeme als auch Generative KI und vermittelt, wie diese mit
klassischen Softwaresystemen kombiniert werden können. Die Teilnehmer:innen
lernen, wie die Architektur für solche hybriden Systeme aussehen muss, um
Skalierbarkeit, Wartbarkeit und Erweiterbarkeit zu gewährleisten.

// end::DE[]

// tag::EN[]
=== What does the module “{curriculum-short}” convey?

The module presents participants with modern software architecture concepts for AI systems as a means of designing powerful, scalable and integrable AI solutions. At the end of the module, participants will be familiar with the key principles of software architecture for AI systems and will be able to apply these to the design and implementation of machine learning and generative AI systems. With the help of the modeling techniques and architecture tools taught, they will be able to seamlessly integrate AI components into existing software systems. The course covers both machine learning systems and generative AI and teaches how these can be combined with classic software systems. Participants learn what the architecture for such hybrid systems must look like in order to ensure scalability, maintainability and extensibility.

// end::EN[]
