
:recommended-duration-in-days: 3
:methodical-credits: 10
:technical-credits: 20
:communicative-credits: 0

// tag::DE[]
=== Dauer, Didaktik und weitere Details

Die Dauer einer Schulung zum Modul {curriculum-short} sollte mindestens {recommended-duration-in-days} Tage betragen, kann aber länger sein. Anbieter können sich durch Dauer, Didaktik, Art und Aufbau der Übungen sowie der detaillierten Kursgliederung voneinander unterscheiden.
Insbesondere die Art der Beispiele und Übungen lässt der Lehrplan komplett offen.
Lizenzierte Schulungen zu {curriculum-short} tragen zur Zulassung zur abschließenden Advanced-Level-Zertifizierungsprüfung folgende Credit Points) bei:

[stripes=none, frame=none, grid=rows]
|===
| Methodische Kompetenz: | {methodical-credits} Punkte
| Technische Kompetenz: | {technical-credits} Punkte
| Kommunikative Kompetenz: | {communicative-credits} Punkte
|===

// end::DE[]

// tag::EN[]
=== Duration, didactics and further details

The duration of a training course on the SWARC4AI module should be at least 3 days, but can be longer. Providers may differ in terms of duration, didactics, type and structure of the exercises and the detailed course structure. In particular, syllabus leaves the type of examples and exercises completely open. Licensed training courses on SWARC4AI contribute to admission to the final Advanced Level certification examination (following credit points):

[stripes=none, frame=none, grid=rows]
|===
| Methodical Competence: | {methodical-credits} Points
| Technical Competence: | {technical-credits} Points
| Communicative Competence: | {communicative-credits} Points
|===

// end::EN[]
