// tag::DE[]
=== Voraussetzungen

Teilnehmer:innen **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

* Ein grundlegendes Verständnis von Künstlicher Intelligenz, Machine Learning und Data Science
* Ein grundlegendes Verständnis für Softwarearchitektur, DevOps und den Entwurf von Softwaresystemen sowie APIs
* Ein grundlegendes Wissen über die Programmiersprache Python und ihre Nutzung für KI-Probleme
* Überblick über gängige Bibliotheken wie scikit-learn, TensorFlow und PyTorch

Wissen in folgenden Bereichen können **hilfreich** für das Verständnis einiger Konzepte sein:

* Erfahrung mit der Kommandozeile auf Linux-Systemen
* Wissen aus der iSAQB CPSA Foundation-Level Schulung für ein allgemeines Verständnis für Softwarearchitektur, Entwurfsmuster und Methodiken

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Prerequisite 1
- Prerequisite 2, etc.

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Area 1:
  * Knowledge 1
  * Experience 2
  * Knowledge 3
  * Experience 4
  * Understanding 5
// end::EN[]
