// tag::DE[]
=== Voraussetzungen

Teilnehmer:innen **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

* Ein grundlegendes Verständnis von Künstlicher Intelligenz, Machine Learning und Data Science
* Ein grundlegendes Verständnis für Softwarearchitektur, DevOps und den Entwurf von Softwaresystemen sowie APIs
* Ein grundlegendes Wissen über die Programmiersprache Python und ihre Nutzung für KI-Probleme
* Überblick über gängige Bibliotheken wie scikit-learn, TensorFlow und PyTorch

Wissen in folgenden Bereichen können **hilfreich** für das Verständnis einiger Konzepte sein:

* Erfahrung mit der Kommandozeile auf Linux-Systemen
* Wissen aus der iSAQB CPSA Foundation-Level Schulung für ein allgemeines Verständnis für Softwarearchitektur, Entwurfsmuster und Methodiken

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants should have the following knowledge and/or experience:

* A basic understanding of artificial intelligence, machine learning and data science
* A basic understanding of software architecture, DevOps and the design of software systems and APIs
* A basic knowledge of the Python programming language and its use for AI problems
* Overview of common libraries such as scikit-learn, TensorFlow and PyTorch

Knowledge in the following areas can be helpful for understanding some concepts

* Experience with the command line interface on Linux systems
* Knowledge from the iSAQB CPSA Foundation level training for a general understanding of software architecture, design patterns and methodologies

// end::EN[]
