// tag::DE[]
=== Voraussetzungen

Teilnehmer:innen **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:


* Ein grundlegendes Verständnis von Künstlicher Intelligenz, Machine Learning und Data Science
* Vertrautheit mit Machine Learning-Methoden, wie Supervised Learning, Unsupervised Learning und Reinforcement Learning, einschließlich Klassifikation, Clustering, Regression und Dimensionality Reduction
* Grundkenntnisse über gängige Algorithmen, wie z. B. lineare und logistische Regression, Entscheidungsbäume, Random Forests, Support Vector Machines, K-Means Clustering sowie neuronale Netze und Deep Learning
* Ein Verständnis der Modellevaluation, einschließlich Cross-Validation, relevanter Metriken (Accuracy, Precision, Recall, F1-Score) und des Bias-Variance Tradeoffs
* Erfahrung mit typischen Frameworks wie scikit-learn, TensorFlow und PyTorch
* Vertrautheit mit Jupyter Notebooks oder ähnlichen Werkzeugen zur schnellen Anwendungsentwicklung (Rapid Application Development, RAD)
* Ein grundlegendes Verständnis der technischen Verfahren hinter Künstlicher Intelligenz, einschließlich Maschinellen Lernens (insbesondere Deep Learning und LLMs) sowie Ansätzen im Bereich Natural Language Processing (NLP) und Transformationsmodellen
* Praktische Erfahrung im Training von Künstlichen Intelligenz-Modellen


// end::DE[]

// tag::EN[]
=== Prerequisites

Participants should have the following knowledge and/or experience:

* A basic understanding of artificial intelligence, machine learning and data science
* A basic understanding of software architecture, DevOps and the design of software systems and APIs
* A basic knowledge of the Python programming language and its use for AI problems
* Overview of common libraries such as scikit-learn, TensorFlow and PyTorch

Knowledge in the following areas can be helpful for understanding some concepts

* Experience with the command line interface on Linux systems
* Knowledge from the iSAQB CPSA Foundation level training for a general understanding of software architecture, design patterns and methodologies

// end::EN[]
