// tag::DE[]
=== Voraussetzungen

Teilnehmer:innen **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:


* Ein grundlegendes Verständnis von Künstlicher Intelligenz, Machine Learning und Data Science
* Vertrautheit mit Machine Learning-Methoden, wie Supervised Learning, Unsupervised Learning und Reinforcement Learning, einschließlich Klassifikation, Clustering, Regression und Dimensionality Reduction
* Grundkenntnisse über gängige Algorithmen, wie z. B. lineare und logistische Regression, Entscheidungsbäume, Random Forests, Support Vector Machines, K-Means Clustering sowie neuronale Netze und Deep Learning
* Ein Verständnis der Modellevaluation, einschließlich Cross-Validation, relevanter Metriken (Accuracy, Precision, Recall, F1-Score) und des Bias-Variance Tradeoffs
* Erfahrung mit typischen Frameworks wie scikit-learn, TensorFlow und PyTorch
* Vertrautheit mit Jupyter Notebooks oder ähnlichen Werkzeugen zur schnellen Anwendungsentwicklung (Rapid Application Development, RAD)
* Ein grundlegendes Verständnis der technischen Verfahren hinter Künstlicher Intelligenz, einschließlich Maschinellen Lernens (insbesondere Deep Learning und LLMs) sowie Ansätzen im Bereich Natural Language Processing (NLP) und Transformationsmodellen
* Praktische Erfahrung im Training von Künstlichen Intelligenz-Modellen


// end::DE[]

// tag::EN[]
=== Prerequisites

Participants should have the following knowledge and/or experience:

-	A basic understanding of artificial intelligence, machine learning and data science
-	Familiarity with machine learning methods, such as supervised learning, unsupervised learning and reinforcement learning, including classification, clustering, regression and dimensionality reduction
-	Basic knowledge of common algorithms, such as linear and logistic regression, decision trees, random forests, support vector machines, K-Means clustering, neural networks and deep learning
-	An understanding of model evaluation, including cross-validation, relevant metrics (accuracy, precision, recall, F1 score) and the bias-variance tradeoff
-	Experience with typical frameworks such as scikit-learn, TensorFlow and PyTorch
-	Familiarity with Jupyter notebooks or similar tools for rapid application development (RAD)
-	A basic understanding of the technical processes behind artificial intelligence, including machine learning (especially deep learning and LLMs) as well as natural language processing (NLP) approaches and transformation models
-	Practical experience in training artificial intelligence models

// end::EN[]
