// tag::DE[]
=== Voraussetzungen

Teilnehmer:innen **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

* Grundlegendes Wissen zu KI, Machine Learning und Data Science
* Machine Learning Methoden wie Supervised, Unsupervised Learning und Reinforcement Learning, z.B Klassifikation, Clustering, Regression, Dimensionality Reduction
* Grundsätzliches Wissen über die typischen Algorithmen wie: Linear/logistic regression, decision trees, random forests, support vector machines, K-means clustering, neural networks and deep learning
* Wissen über Model evaluation: Cross-validation, Metrics (accuracy, precision, recall, F1-score), Bias-variance tradeoff
* Erfahrung mit typischen Frameworks wie sk-learn, TensorFlow, PyTorch
* Erfahrung mit Jupyter Notebooks oder ähnlichen Rapid Application Development (RAD) Werkzeugen
* Wissen über die technischen Verfahren hinter KI, einschließlich: Maschinelles Lernen inkl. Deep Learning und LLMs, NLP-Ansätze (Natural Language Processing), Transformationsmodelle
* Praktische Erfahrung mit Trainieren von Künstlichen Intelligenz Modellen

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Prerequisite 1
- Prerequisite 2, etc.

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Area 1:
  * Knowledge 1
  * Experience 2
  * Knowledge 3
  * Experience 4
  * Understanding 5
// end::EN[]
