=== {learning-goals}

// tag::DE[]


[[LZ-5-1]]
==== LZ 5-1: (Hardware)-Anforderungen an Training und Inferenz kennen

Die Teilnehmer:innen kennen unterschiedliche (Hardware)-Anforderungen für beispielsweise TPU, NPU, LPU, GPU oder CPU an Training und Inferenz.

[[LZ-5-2]]
==== LZ 5-2: Trade-Offs verschiedener Modellarchitekturen bezüglich der Qualitätsmerkmale kennen

Die Teilnehmer:innen können beispielhaft Trade-Offs verschiedener Modellarchitekturen bezüglich der Qualitätsmerkmale nennen. Insbesondere für Skalierung, Effizienz und Speicherlast sollten die Teilnehmer:innen die Trade-Offs sowie die Vor- und Nachteile von wichtigen Architekturen wie beispielsweise RNNs und Transformern kennen.


[[LZ-5-3]]
==== LZ 5-3: Verschiedene Qualitätsmerkmale eines ML-Modells abstimmen

Die Teilnehmer:innen kennen Möglichkeiten, um verschiedene Qualitätsmerkmale wie Genauigkeit, Effizienz und Speicherlast eines ML-Modells abzustimmen und gegeneinander
einzutauschen. Insbesondere kennen die Teilnehmer:innen die folgenden Techniken:

* Quantisierung
* Pruning
* Destillierung
* LoRA

[[LZ-5-4]]
==== LZ 5-4: Kosten, Stromverbrauch und nachhaltige Nutzung von KI (Green IT) verstehen

Die Teilnehmer:innen erlangen ein Verständnis für Kosten, Stromverbrauch und nachhaltige Nutzung von KI (Green IT). Insbesondere wissen die Teilnehmer:innen, wie man KI-Modelle und -Systeme entwickelt, die ressourcenschonend arbeiten, indem sie Speicher, Rechenleistung und Speicherplatz effizient nutzen.

[[LZ-5-5]]
==== LZ 5-5: MLOps für die Automatisierung des Life-Cycles eines Data-Science-Projekts überblicken

Die Teilnehmer:innen kennen den Begriff MLOps für die Automatisierung des Life-Cycles eines Data-Science-Projekts sowie den Zusammenhang mit DevOps.

[OPTIONAL]
Die Teilnehmer:innen verstehen anhand eines Praxisbeispiels, wie eine MLOps-Pipeline aussehen kann und welche Einsichten diese auf die Parameter, Metriken usw. bietet.

[[LZ-5-6]]
==== LZ 5-6: Modelltraining, Parameter, Metriken und Ergebnisse tracken

Die Teilnehmer:innen haben ein Verständnis vom Tracking im Modelltraining, Parametern, Metriken und Ergebnissen.

[[LZ-5-7]]
==== LZ 5-7: Modellevaluation, Systemevaluation und fachliche Nutzenbewertung unterscheiden und geeignete Evaluationsansätze für KI-Systeme auswählen.

Die Teilnehmer:innen überblicken Ansätze zur Evaluation von ML-Modellen und darauf aufbauenden KI-Systemen.

[[LZ-5-8]]
==== LZ 5-8: Arten von Drift sowie mögliche Ursachen und Lösungsansätze dafür kennen

Die Teilnehmer:innen kennen verschiedene Arten von Drift, wie beispielsweise Daten-Drift oder Modell-Drift, sowie mögliche Ursachen und Lösungsansätze dafür.

[[LZ-5-9]]
==== LZ 5-9: CI/CD-Pipelines, Modellmanagement und Deployment-Strategien für KI-Modelle überblicken

Die Teilnehmer:innen haben ein Verständnis von CI/CD-Pipelines, Modellmanagement und Deployment-Strategien für KI-Modelle.

Die Teilnehmer:innen kennen eine Auswahl verschiedener Deployment-Möglichkeiten von KI-Modellen:

* API Deployment
* Embedded Deployment
* Batch Prediction
* Streaming
* Containerization
* Serverless Deployment
* Cloud Services

[OPTIONAL]
Die Teilnehmer:innen kennen gängige Plattformen und Werkzeuge für die Modellbereitstellung sowie Erstellung von POCs und verstehen die konzeptionelle Funktionsweise.


[[LZ-5-10]]
==== LZ 5-10: Vor- und Nachteile von SaaS und Self-Hosting nennen sowie Make-or-Buy-Entscheidungen anhand von Qualitätsanforderungen treffen

Die Teilnehmer:innen kennen die Vor- und Nachteile von SaaS und Self-Hosting und können dazwischen abwägen.

Die Teilnehmer:innen sind in der Lage, Make-or-Buy Entscheidungen für MLOps- und KI-Plattform Systemen/Komponenten anhand von Qualitätsanforderungen, Kosten, Risiko, Compliance und Integrationsaufwand zu treffen.

[OPTIONAL]
Die Teilnehmer:innen überblicken bekannte SaaS-KI-Lösungen, wie beispielsweise Azure OpenAI Services.

[[LZ-5-11]]
==== LZ 5-11: Monitoring und Observability für KI-Systeme konzipieren, insbesondere für Drift, Qualitätsverlust, Kosten, Latenz, Sicherheitsereignisse und Governance-relevante Nachweise.

Die Teilnehmer:innen verstehen die Notwendigkeit für Monitoring, auch im Hinblick auf KI-spezifische Anforderungen wie das Tracking von Drift.

Die Teilnehmer:innen kennen relevante Metriken wie beispielsweise Accuracy, Precision, Recall, F1-Score, MAE, MSE, Perplexity, Latenz, Durchsatz und Ressourcenauslastung und verstehen, warum diese für das Monitoring relevant sind.

Die Teilnehmer:innen kennen Beispiel-Werkzeuge für Monitoring. Dies betrifft sowohl allgemeine Werkzeuge, wie beispielsweise Prometheus & Grafana,
als auch ML-spezifische wie beispielsweise MLflow.

[[LZ-5-12]]
==== LZ 5-12: Nutzer-Feedback sowie Methoden und Werkzeuge zur Sammlung von Nutzer-Feedback verstehen

Die Teilnehmer:innen verstehen den Nutzen von Nutzer-Feedback für das weitere Modelltraining.
Darüber hinaus kennen die Teilnehmer:innen verschiedene Methoden und Werkzeuge zur Sammlung von Nutzer-Feedback, wie beispielsweise die Auswahl zwischen mehreren Antworten oder Flagging in Gradio.

[OPTIONAL]
Die Teilnehmer:innen kennen weitere Methoden zur Gewinnung von Nutzer-Feedback, wie beispielsweise RLHF, RLAIF und DPO.


[[LZ-5-13]]
==== LZ 5-13: [OPTIONAL] Klassen von MLOps-Werkzeugen und Plattformen sowie wesentliche Auswahlkriterien für ihren Einsatz kennen.

Die Teilnehmer:innen kennen bekannte MLOps-Werkzeuge und End-to-End Plattformen,wie beispielsweise:

* Domino Data Lab, h2o.ai, DVC, activeloop, aporia, argo, arize, bentoML, comet ML, DagsHub, Databricks MLOps Stacks, Feast, Kedro, Metaflow, MLflow, MLRun, prefect, PrimeHub, Weights & Biases, WhyLabs, zenML, KNIME, RapidMiner, NVIDIA AI Enterprise, watsonx.ai
* OpenSource: MLFlow, Kubeflow, ClearML
* PaaS: AWS SageMaker, Azure ML, Google Vertex AI

// end::DE[]






// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Know (hardware) requirements for training and inference

Participants know the different (hardware) requirements for training and inference, for example for TPUs, NPUs, LPUs, GPUs, or CPUs.

[[LG-5-2]]
==== LG 5-2: Know the trade-offs of different model architectures with regard to quality characteristics
Participants can give examples of trade-offs between different model architectures with regard to quality characteristics. Particularly for scaling, efficiency, and memory footprint, participants should know the trade-offs as well as the advantages and disadvantages of important architectures such as RNNs and transformers.

[[LG-5-3]]
==== LG 5-3: Adjust different quality features of an ML model

Participants know ways to balance and trade off different quality characteristics of an ML model, such as accuracy, efficiency, and memory footprint. In particular, they know the following techniques:

* Quantization
* Pruning
* Distillation
* LoRA



[[LG-5-4]]
==== LG 5-4: Understand the costs, power consumption, and sustainable use of AI (Green IT)

Participants gain an understanding of the costs, power consumption, and sustainable use of AI (Green IT). In particular, they know how to develop AI models and systems that operate efficiently by making economical use of memory, compute capacity, and storage space.


[[LG-5-5]]
==== LG 5-5: Gain an overview of MLOps for automating the life cycle of a data science project

Participants know the term MLOps for automating the life cycle of a data science project and its relationship to DevOps.

[OPTIONAL]
Using a practical example, participants understand what an MLOps pipeline can look like and what insights it provides into parameters, metrics, and other aspects.


[[LG-5-6]]
==== LG 5-6: Track model training, parameters, metrics, and results

Participants understand tracking in model training, including parameters, metrics, and results.


[[LG-5-7]]
==== LG 5-7: Distinguish model evaluation, system evaluation, and assessment of business value, and select suitable evaluation approaches for AI systems

Participants have an overview of approaches for evaluating ML models and the AI systems based on them.


[[LG-5-8]]
==== LG 5-8: Know types of drift and possible causes and solutions for them

Participants are familiar with different types of drift, such as data drift or model drift, as well as possible causes and solutions.


[[LG-5-9]]
==== LG 5-9: Gain an overview of CI/CD pipelines, model management, and deployment strategies for AI models

Participants understand CI/CD pipelines, model management, and deployment strategies for AI models.

Participants know a selection of different deployment options for AI models:

* API deployment
* Embedded deployment
* Batch prediction
* Streaming
* Containerization
* Serverless deployment
* Cloud services

[OPTIONAL]
Participants know common platforms and tools for model provision and for creating POCs and understand how they work conceptually.


[[LG-5-10]]
==== LG 5-10: State the advantages and disadvantages of SaaS and self-hosting and make make-or-buy decisions based on quality requirements

Participants know the advantages and disadvantages of SaaS and self-hosting and can weigh them against each other.

Participants can make make-or-buy decisions for MLOps and AI platform systems or components based on quality requirements, cost, risk, compliance, and integration effort.

[OPTIONAL]
Participants have an overview of well-known SaaS AI solutions, such as Azure OpenAI Services.


[[LG-5-11]]
==== LG 5-11: Design monitoring and observability for AI systems, particularly for drift, quality degradation, costs, latency, security events, and governance-relevant evidence

Participants understand the need for monitoring, including with regard to AI-specific requirements such as drift tracking.

Participants know relevant metrics such as accuracy, precision, recall, F1 score, MAE, MSE, perplexity, latency, throughput, and resource utilization, and understand why they are relevant for monitoring.

Participants know example monitoring tools. These include both general-purpose tools, such as Prometheus and Grafana, and ML-specific tools, such as MLflow.


[[LG-5-12]]
==== LG 5-12: Understand user feedback and methods and tools for collecting it

Participants understand the benefits of user feedback for further model training. They also know various methods and tools for collecting user feedback, such as choosing between multiple answers or flagging in Gradio.

[OPTIONAL]
Participants know further methods for obtaining user feedback, such as RLHF, RLAIF, and DPO.


[[LG-5-13]]
==== LG 5-13: [OPTIONAL] Know classes of MLOps tools and platforms and essential criteria for selecting them

Participants know well-known MLOps tools and end-to-end platforms, such as:

* Domino Data Lab, h2o.ai, DVC, activeloop, aporia, argo, arize, bentoML, comet ML, DagsHub, Databricks MLOps Stacks, Feast, Kedro, Metaflow, MLflow, MLRun, prefect, PrimeHub, Weights & Biases, WhyLabs, zenML, KNIME, RapidMiner, NVIDIA AI Enterprise, watsonx.ai
* Open source: MLflow, Kubeflow, ClearML
* PaaS: AWS SageMaker, Azure ML, Google Vertex AI



// end::EN[]
